osx_image: xcode7.3

os:
  - osx

sudo: required
dist: trusty

language: c

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
- brew install graphicsmagick
- brew install libpng
- brew install openjpeg
- wget https://github.com/Stemn/Assets/raw/master/libicns-0.8.1.tar.gz -O libicns.tar.gz
- tar -xvf libicns.tar.gz
- cd libicns-0.8.1
- ./configure
- make
- make install
- cd ..

install:
- git reset --hard HEAD
- nvm install 6
- npm install

script:
- node ./scripts/publish/index.js # this will create release.json in release/mac
- node_modules/.bin/build --mac --publish always
- node_modules/.bin/build --linux --publish always

notifications:
  email: false
