osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

install:
- nvm install 6
- npm install electron-builder@next # force install next version to test electron-builder
- npm install

script:
- node_modules/.bin/build --mac --publish onTagOrDraft
- node_modules/.bin/build --linux --publish onTagOrDraft

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
