osx_image: xcode7.3

os:
  - osx

sudo: required
dist: trusty

language: c

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
- brew install graphicsmagick
- brew install libpng
- brew install openjpeg
- brew install icns2png

install:
- git reset --hard HEAD
- nvm install 6
- npm install electron-builder@next # force install next version to test electron-builder
- npm install

script:
- node_modules/.bin/build --linux --publish always
- node_modules/.bin/build --mac --publish always
