osx_image: xcode7.3

os:
  - osx

sudo: required
dist: trusty

language: c

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
- brew install graphicsmagick
- brew install libpng
- brew install openjpeg
- wget http://downloads.sourceforge.net/project/icns/libicns-0.8.1.tar.gz -O libicns.tar.gz
- tar -xvf libicns.tar.gz
- cd libicns-0.8.1
- ./configure
- make
- make install

install:
- git reset --hard HEAD
- nvm install 6
- npm install electron-builder@next # force install next version to test electron-builder
- npm install
- ls node_modules/.bin

script:
- node_modules/.bin/build --linux --publish always
- node_modules/.bin/build --mac --publish always
